### ISSUE TITLE
Дизайн VKMMediaNode

### ISSUE THREAD

**Issue by pavelosipov** [nikolaevigor/vkmusic#1]
``` objective-c
@interface VKMMediaNode : VKMNode
// Size of the media. Can not be nil.
@property (nonatomic, nonnull) NSUInteger *size;
// Type of the media. Can not be nil.
@property (nonatomic, nonnull) NSString *type;
@end
```

В данном случае size - это простой целочисленный тип. Указатель здесь явно лишний.

**Comment by pavelosipov** [comment]
Вторая ошибка в дизайне этого класса состоит в том, что `nonnull` контракт не поддержан соответствующим инитором.  Я могу создать объект этого класса как `[VMKMediaNode new]` и тип будет нулевым.

**Comment by nikolaevigor** [comment]
@pavelosipov Убрал указатель. Но с ним пришлось убрать модификатор `nonnull`.
Нужно делать проверку на нулевое значение в первичном инитере?
Если я запрещаю вызов `init`, то вызов new также запретится? Или нужно `new` отдельно прописывать каждый раз?

**Comment by pavelosipov** [comment]
1. Да, `new` также запретится.
2. Аргументы базовых типов также нужно передавать по значению и проверять на попадание в допустимый диапазон, если нужно.

**Comment by nikolaevigor** [comment]
Спасибо. В следующем коммите всё поправим.
