### ISSUE TITLE
Дизайн VKMAudioNode

### ISSUE THREAD

**Issue by pavelosipov** [nikolaevigor/vkmusic#2]
1. Втроенные типы ошибочно держатся по указателю.
2. Имена параметров принято писать с маленькой буквы. Я имею в виду ваш метод `initWithName:Artist:`.
3. В иниторе лучше избегать использования `self`.

**Comment by nikolaevigor** [comment]
Поправил NSTimeInterval.
Поправил `artist:`
Как быть с `self`, если у меня в родительском классе name является `@property`, а не ivar?

**Comment by pavelosipov** [comment]
Дело в том, что @property - это не более чем директива компилятору сгенерировать следующее:
1. ivar с именем `_propertyName`.
2. setter с именением `setPropertyName`
3. getter с именением `propertyName`.
Таким образом, ivar на самом деле у вас есть.
Рекомендация избегания использования `self` обусловлена желанием предотвратить ситуации, когда setter переопределен в классе-наследнике и получается, что он будет вызван до того, как завершилась его инициализация.

**Comment by nikolaevigor** [comment]
я немного не понимаю. Почему, если я пишу в суперклассе `@property NSString *tmp;`, то я потом не могу в наследнике использовать переменную _tmp?
Нужно прописывать в .h-файле суперкласса в фигурных скобках `NSString *_tmp;`, а потом в .m-файле суперкласса `@synthesize tmp = _tmp`? Если да, то почему?

**Comment by pavelosipov** [comment]
Переменная `NSString *_tmp` генерируется в m-файле суперкласса, поэтому она публично не видна. Если нужен доступ к переменным суперкласса, то можно объявить ее в фигурных скобках суперкласса в h-файле. По умолчанию она будет приватной и доступ к ней будет только у методов суперкласса. Чтобы резрешить обращаться к ней методам класса-наследника, нужно объявить ее как `protected`:

``` objective-c
@interface PRKBase {
@protected
   NSString *_name;
}
@end
```

Ну лучше этим делом не злоупотреблять.

**Comment by nikolaevigor** [comment]
Понял, спасибо. К следующему коммиту поправим.
